version: "3.8"
services:
  postgres:
    container_name: massacre_postgres
    image: postgres:15
    restart: always
    environment:
      DATABASE_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: massacre
      POSTGRES_DB: halving-massacre
    ports:
      - 5433:5432

  app:
    build:
      context: ./
      target: runner
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://root:massacre@postgres:5432/halving-massacre"
    depends_on:
      - postgres
