version: "3.8"
services:
  postgres:
    container_name: massacre_postgres
    image: postgres:15
    restart: always
    environment:
      DATABASE_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: massacre
      POSTGRES_DB: halving-massacre
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -h localhost -d halving-massacre"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 360s
  massacre-migrate:
    image: node:18-alpine3.16
    container_name: massacre-migrate
    environment:
      DATABASE_URL: postgresql://root:massacre@massacre_postgres/halving-massacre
    entrypoint: [ 'sh', '-c', 'cd code && npm install --no-save --quiet prisma@5.12.0 && npx prisma migrate deploy']
    volumes:
      - ./prisma:/code/prisma
    depends_on:
      postgres:
        condition: service_healthy
  app:
    container_name: halving-massacre
    restart: always
    build:
      context: ./
      target: runner
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://root:massacre@postgres:5432/halving-massacre"
    depends_on:
      - postgres
